const GeoLayout service_counter_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, service_counter_service_counter_model_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, service_counter_service_counter_model_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, service_counter_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, service_counter_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
