const GeoLayout patty_patty_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, patty_patty_model_mesh_layer_1_mat_override_burger_patty_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout patty_patty_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, patty_patty_model_mesh_layer_1_mat_override_pot_liquid_burnt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout patty_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 67),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, patty_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, patty_patty_model_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, patty_patty_switch_opt1),
					GEO_BRANCH(1, patty_patty_switch_opt2),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, patty_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
