extern const GeoLayout patty_patty_switch_opt1[];
extern const GeoLayout patty_patty_switch_opt2[];
extern const GeoLayout patty_geo[];
extern Lights1 patty_burger_patty_raw_lights;
extern Lights1 patty_burger_patty_lights;
extern Lights1 patty_pot_liquid_burnt_lights;
extern u8 patty_patty_raw_ci8[];
extern u8 patty_patty_raw_pal_rgba16[];
extern u8 patty_patty_rgba16[];
extern u8 patty_pot_liquid_burnt_ci8[];
extern u8 patty_pot_liquid_burnt_pal_rgba16[];
extern Vtx patty_patty_model_mesh_layer_1_vtx_0[78];
extern Gfx patty_patty_model_mesh_layer_1_tri_0[];
extern Gfx mat_patty_burger_patty_raw[];
extern Gfx mat_revert_patty_burger_patty_raw[];
extern Gfx mat_patty_burger_patty[];
extern Gfx mat_revert_patty_burger_patty[];
extern Gfx mat_patty_pot_liquid_burnt[];
extern Gfx mat_revert_patty_pot_liquid_burnt[];
extern Gfx patty_patty_model_mesh_layer_1[];
extern Gfx patty_patty_model_mesh_layer_1_mat_override_burger_patty_0[];
extern Gfx patty_patty_model_mesh_layer_1_mat_override_pot_liquid_burnt_1[];
extern Gfx patty_material_revert_render_settings[];
