extern const GeoLayout box_box_label_switch_opt1[];
extern const GeoLayout box_box_label_switch_opt2[];
extern const GeoLayout box_box_label_switch_opt3[];
extern const GeoLayout box_box_label_switch_opt4[];
extern const GeoLayout box_box_label_switch_opt5[];
extern const GeoLayout box_box_label_switch_opt6[];
extern const GeoLayout box_box_label_switch_opt7[];
extern const GeoLayout box_box_label_switch_opt8[];
extern const GeoLayout box_box_label_switch_opt9[];
extern const GeoLayout box_geo[];
extern Lights1 box_box_label_steak_lights;
extern Lights1 box_box_label_cheese_lights;
extern Lights1 box_box_label_onion_lights;
extern Lights1 box_box_label_lettuce_lights;
extern Lights1 box_box_label_buns_lights;
extern Lights1 box_box_label_tomato_lights;
extern Lights1 box_box_label_mushroom_lights;
extern Lights1 box_box_label_chicken_lights;
extern Lights1 box_box_label_sausage_lights;
extern Lights1 box_box_label_dough_lights;
extern Lights1 box_box_lights;
extern Lights1 box_box_hole_lights;
extern u8 box_box_label_steak_ci4[];
extern u8 box_box_label_steak_pal_rgba16[];
extern u8 box_box_label_cheese_ci4[];
extern u8 box_box_label_cheese_pal_rgba16[];
extern u8 box_box_label_onion_ci4[];
extern u8 box_box_label_onion_pal_rgba16[];
extern u8 box_box_label_lettuce_ci4[];
extern u8 box_box_label_lettuce_pal_rgba16[];
extern u8 box_box_label_buns_ci4[];
extern u8 box_box_label_buns_pal_rgba16[];
extern u8 box_box_label_tomato_ci4[];
extern u8 box_box_label_tomato_pal_rgba16[];
extern u8 box_box_label_mushroom_ci4[];
extern u8 box_box_label_mushroom_pal_rgba16[];
extern u8 box_box_label_chicken_ci4[];
extern u8 box_box_label_chicken_pal_rgba16[];
extern u8 box_box_label_sausage_ci4[];
extern u8 box_box_label_sausage_pal_rgba16[];
extern u8 box_box_label_dough_ci4[];
extern u8 box_box_label_dough_pal_rgba16[];
extern u8 box_box_rgba16[];
extern Vtx box_box_label_model_mesh_layer_4_vtx_0[4];
extern Gfx box_box_label_model_mesh_layer_4_tri_0[];
extern Vtx box_box_lid_mesh_layer_1_vtx_0[48];
extern Gfx box_box_lid_mesh_layer_1_tri_0[];
extern Vtx box_box_model_mesh_layer_1_vtx_0[112];
extern Gfx box_box_model_mesh_layer_1_tri_0[];
extern Vtx box_box_model_mesh_layer_1_vtx_1[7];
extern Gfx box_box_model_mesh_layer_1_tri_1[];
extern Gfx mat_box_box_label_steak[];
extern Gfx mat_revert_box_box_label_steak[];
extern Gfx mat_box_box_label_cheese[];
extern Gfx mat_revert_box_box_label_cheese[];
extern Gfx mat_box_box_label_onion[];
extern Gfx mat_revert_box_box_label_onion[];
extern Gfx mat_box_box_label_lettuce[];
extern Gfx mat_revert_box_box_label_lettuce[];
extern Gfx mat_box_box_label_buns[];
extern Gfx mat_revert_box_box_label_buns[];
extern Gfx mat_box_box_label_tomato[];
extern Gfx mat_revert_box_box_label_tomato[];
extern Gfx mat_box_box_label_mushroom[];
extern Gfx mat_revert_box_box_label_mushroom[];
extern Gfx mat_box_box_label_chicken[];
extern Gfx mat_revert_box_box_label_chicken[];
extern Gfx mat_box_box_label_sausage[];
extern Gfx mat_revert_box_box_label_sausage[];
extern Gfx mat_box_box_label_dough[];
extern Gfx mat_revert_box_box_label_dough[];
extern Gfx mat_box_box[];
extern Gfx mat_revert_box_box[];
extern Gfx mat_box_box_hole[];
extern Gfx mat_revert_box_box_hole[];
extern Gfx box_box_label_model_mesh_layer_4[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_cheese_0[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_onion_1[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_lettuce_2[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_buns_3[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_tomato_4[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_mushroom_5[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_chicken_6[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_sausage_7[];
extern Gfx box_box_label_model_mesh_layer_4_mat_override_box_label_dough_8[];
extern Gfx box_box_lid_mesh_layer_1[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_cheese_0[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_onion_1[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_lettuce_2[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_buns_3[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_tomato_4[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_mushroom_5[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_chicken_6[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_sausage_7[];
extern Gfx box_box_lid_mesh_layer_1_mat_override_box_label_dough_8[];
extern Gfx box_box_model_mesh_layer_1[];
extern Gfx box_material_revert_render_settings[];
