const GeoLayout chicken_cut_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 67),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chicken_cut_chicken_cut_model_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, chicken_cut_chicken_cut_model_mesh_layer_5),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, chicken_cut_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, chicken_cut_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
