extern const GeoLayout chicken_cut_geo[];
extern Lights1 chicken_cut_chicken_raw_lights;
extern Lights1 chicken_cut_chicken_spec_lights;
extern u8 chicken_cut_chicken_raw_ci8[];
extern u8 chicken_cut_chicken_raw_pal_rgba16[];
extern u8 chicken_cut_chicken_spec_rgba16[];
extern Vtx chicken_cut_chicken_cut_model_mesh_layer_1_vtx_0[221];
extern Gfx chicken_cut_chicken_cut_model_mesh_layer_1_tri_0[];
extern Vtx chicken_cut_chicken_cut_model_mesh_layer_5_vtx_0[190];
extern Gfx chicken_cut_chicken_cut_model_mesh_layer_5_tri_0[];
extern Gfx mat_chicken_cut_chicken_raw[];
extern Gfx mat_revert_chicken_cut_chicken_raw[];
extern Gfx mat_chicken_cut_chicken_spec[];
extern Gfx mat_revert_chicken_cut_chicken_spec[];
extern Gfx chicken_cut_chicken_cut_model_mesh_layer_1[];
extern Gfx chicken_cut_chicken_cut_model_mesh_layer_5[];
extern Gfx chicken_cut_material_revert_render_settings[];
