#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_cannon_circle_base),
		GEO_ASM(0, geo_movtex_pause_control),
		GEO_ASM(0x1601, geo_movtex_draw_nocolor),
		GEO_ASM(0x1601, geo_movtex_draw_water_regions),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_LAYER_ALPHA_castle_grounds_seg7_dl_0700A860_mesh_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_LAYER_ALPHA_castle_grounds_seg7_dl_0700BA20_mesh_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_LAYER_ALPHA_castle_grounds_seg7_dl_0700BC68_mesh_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_final_revert_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_LAYER_OPAQUE_castle_grounds_seg7_dl_07006D70_mesh_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_LAYER_OPAQUE_castle_grounds_seg7_dl_070095F0_mesh_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_LAYER_OPAQUE_castle_grounds_seg7_dl_0700C210_mesh_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_final_revert_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, castle_grounds_dl_LAYER_OPAQUE_DECAL_castle_grounds_seg7_dl_0700C430_mesh_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, castle_grounds_dl_final_revert_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_grounds_dl_LAYER_TRANSPARENT_DECAL_castle_grounds_seg7_dl_0700B1D0_mes_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_grounds_dl_final_revert_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
