extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_Side_lights;
extern Lights1 ssl_dl_Top_lights;
extern u8 ssl_dl_bob_textures_04000_rgba16_rgba16[];
extern u8 ssl_dl_bob_textures_02000_rgba16_ci8[];
extern u8 ssl_dl_bob_textures_02000_rgba16_pal_rgba16[];
extern u8 ssl_dl__7_rgba16_ci8[];
extern u8 ssl_dl__7_rgba16_pal_rgba16[];
extern Vtx ssl_dl_Platforms_mesh_layer_1_vtx_0[32];
extern Gfx ssl_dl_Platforms_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Platforms_mesh_layer_1_vtx_1[8];
extern Gfx ssl_dl_Platforms_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_Quicksand_mesh_layer_1_vtx_0[4];
extern Gfx ssl_dl_Quicksand_mesh_layer_1_tri_0[];
extern Gfx mat_ssl_dl_Side[];
extern Gfx mat_revert_ssl_dl_Side[];
extern Gfx mat_ssl_dl_Top[];
extern Gfx mat_revert_ssl_dl_Top[];
extern Gfx mat_ssl_dl_Quicksand[];
extern Gfx mat_revert_ssl_dl_Quicksand[];
extern Gfx ssl_dl_Platforms_mesh_layer_1[];
extern Gfx ssl_dl_Quicksand_mesh_layer_1_with_revert[];
