extern const GeoLayout ocTest_area_1_geo[];
extern const GeoLayout ocTest_area_1[];
extern const Collision ocTest_area_1_collision[];
extern const MacroObject ocTest_area_1_macro_objs[];
extern Lights1 ocTest_dl_Edges_lights;
extern Lights1 ocTest_dl_Snow_Slippery_lights;
extern Lights1 ocTest_dl_Snow_lights;
extern Lights1 ocTest_dl_Wood_lights;
extern u8 ocTest_dl_ccm_textures_03000_rgba16_ci8[];
extern u8 ocTest_dl_ccm_textures_03000_rgba16_pal_rgba16[];
extern u8 ocTest_dl_ccm_textures_08800_rgba16_ci8[];
extern u8 ocTest_dl_ccm_textures_08800_rgba16_pal_rgba16[];
extern u8 ocTest_dl_ccm_textures_08000_rgba16_ci8[];
extern u8 ocTest_dl_ccm_textures_08000_rgba16_pal_rgba16[];
extern Vtx ocTest_dl_Room_mesh_layer_1_vtx_0[247];
extern Gfx ocTest_dl_Room_mesh_layer_1_tri_0[];
extern Vtx ocTest_dl_Room_mesh_layer_1_vtx_1[8];
extern Gfx ocTest_dl_Room_mesh_layer_1_tri_1[];
extern Vtx ocTest_dl_Room_mesh_layer_1_vtx_2[30];
extern Gfx ocTest_dl_Room_mesh_layer_1_tri_2[];
extern Vtx ocTest_dl_Room_mesh_layer_1_vtx_3[38];
extern Gfx ocTest_dl_Room_mesh_layer_1_tri_3[];
extern Gfx mat_ocTest_dl_Edges[];
extern Gfx mat_revert_ocTest_dl_Edges[];
extern Gfx mat_ocTest_dl_Snow_Slippery[];
extern Gfx mat_revert_ocTest_dl_Snow_Slippery[];
extern Gfx mat_ocTest_dl_Snow[];
extern Gfx mat_revert_ocTest_dl_Snow[];
extern Gfx mat_ocTest_dl_Wood[];
extern Gfx mat_revert_ocTest_dl_Wood[];
extern Gfx ocTest_dl_Room_mesh_layer_1_with_revert[];
