extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_Edges_lights;
extern Lights1 ccm_dl_Snow_Slippery_lights;
extern Lights1 ccm_dl_Snow_lights;
extern Lights1 ccm_dl_Wood_lights;
extern u8 ccm_dl_ccm_textures_03000_rgba16_ci8[];
extern u8 ccm_dl_ccm_textures_03000_rgba16_pal_rgba16[];
extern u8 ccm_dl_ccm_textures_08800_rgba16_ci8[];
extern u8 ccm_dl_ccm_textures_08800_rgba16_pal_rgba16[];
extern u8 ccm_dl_ccm_textures_08000_rgba16_ci8[];
extern u8 ccm_dl_ccm_textures_08000_rgba16_pal_rgba16[];
extern Vtx ccm_dl_Room_mesh_layer_1_vtx_0[247];
extern Gfx ccm_dl_Room_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Room_mesh_layer_1_vtx_1[8];
extern Gfx ccm_dl_Room_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Room_mesh_layer_1_vtx_2[30];
extern Gfx ccm_dl_Room_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Room_mesh_layer_1_vtx_3[38];
extern Gfx ccm_dl_Room_mesh_layer_1_tri_3[];
extern Gfx mat_ccm_dl_Edges[];
extern Gfx mat_revert_ccm_dl_Edges[];
extern Gfx mat_ccm_dl_Snow_Slippery[];
extern Gfx mat_revert_ccm_dl_Snow_Slippery[];
extern Gfx mat_ccm_dl_Snow[];
extern Gfx mat_revert_ccm_dl_Snow[];
extern Gfx mat_ccm_dl_Wood[];
extern Gfx mat_revert_ccm_dl_Wood[];
extern Gfx ccm_dl_Room_mesh_layer_1_with_revert[];
