const GeoLayout pizza_pizza_cheese[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pizza_pizza_cheese_switch_option_pizza_cheese_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_cheese_melted[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pizza_pizza_cheese_switch_option_pizza_cheese_model_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_chicken[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pizza_pizza_chicken_switch_option_pizza_chicken_model_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pizza_pizza_chicken_switch_option_pizza_chicken_model_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_chicken_baked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pizza_pizza_chicken_baked_switch_option_pizza_chicken_baked_model_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pizza_pizza_chicken_baked_switch_option_pizza_chicken_baked_model_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_dough_baked[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pizza_pizza_dough_baked_switch_option_pizza_dough_baked_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_dough_burnt[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pizza_pizza_dough_burnt_switch_option_pizza_dough_burnt_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_mushroom[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pizza_pizza_mushroom_switch_option_pizza_mushroom_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_sausage[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pizza_pizza_sausage_switch_option_pizza_sausage_model_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pizza_pizza_sausage_switch_option_pizza_sausage_model_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_pizza_tomato_sauce[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pizza_pizza_tomato_sauce_switch_option_pizza_tomato_sauce_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout pizza_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 69),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, pizza_cheese_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, pizza_pizza_cheese),
					GEO_BRANCH(1, pizza_pizza_cheese_melted),
				GEO_CLOSE_NODE(),
				GEO_SWITCH_CASE(0, pizza_chicken_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, pizza_pizza_chicken),
					GEO_BRANCH(1, pizza_pizza_chicken_baked),
				GEO_CLOSE_NODE(),
				GEO_SWITCH_CASE(0, pizza_dough_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, pizza_pizza_dough_model_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, pizza_pizza_dough_baked),
					GEO_BRANCH(1, pizza_pizza_dough_burnt),
				GEO_CLOSE_NODE(),
				GEO_SWITCH_CASE(0, pizza_mushroom_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, pizza_pizza_mushroom),
				GEO_CLOSE_NODE(),
				GEO_SWITCH_CASE(0, pizza_sausage_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, pizza_pizza_sausage),
				GEO_CLOSE_NODE(),
				GEO_SWITCH_CASE(0, pizza_tomato_sauce_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, pizza_pizza_tomato_sauce),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pizza_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, pizza_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
