const GeoLayout onion_onion_whole[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 108, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, onion_onion_whole_so_onion_whole_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout onion_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 62),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, onion_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 117, 0, onion_segment_1_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 72, 0, onion_segment_2_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 27, 0, onion_segment_3_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -17, 0, onion_segment_4_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -62, 0, onion_segment_5_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -98, 0, onion_segment_6_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, onion_onion_whole),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, onion_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
