const GeoLayout mushroom_mushroom_whole[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 109, 90, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mushroom_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 62),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, mushroom_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 109, 90, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -93, 14, 0, mushroom_segment_1_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -60, 14, 0, mushroom_segment_2_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -20, 5, 0, mushroom_segment_3_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 5, 0, mushroom_segment_4_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 14, 0, mushroom_segment_5_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 93, 14, 0, mushroom_segment_6_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, mushroom_mushroom_whole),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mushroom_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
