const GeoLayout tomato_tomato_whole[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 82, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, tomato_tomato_whole_so_tomato_whole_mdl_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout tomato_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 62),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, tomato_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 82, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 88, 0, tomato_segment_1_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, tomato_segment_2_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, tomato_segment_3_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -27, 0, tomato_segment_4_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -61, 0, tomato_segment_5_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -78, 0, tomato_segment_6_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, tomato_tomato_whole),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, tomato_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
