extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl_slide_planks_rgba16[];
extern u8 jrb_dl_ship_wood_secondary_rgba16[];
extern u8 jrb_dl_ship_wood_tertiary_rgba16[];
extern u8 jrb_dl_window_drj_rgba16[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_0[27];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_1[154];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_2[308];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx jrb_dl_Level_Mesh_mesh_layer_1_vtx_3[72];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1_tri_3[];
extern Gfx mat_jrb_dl_wood_layer1_area1[];
extern Gfx mat_revert_jrb_dl_wood_layer1_area1[];
extern Gfx mat_jrb_dl_wood_secondary_layer1_area1[];
extern Gfx mat_revert_jrb_dl_wood_secondary_layer1_area1[];
extern Gfx mat_jrb_dl_wood_tertiary_layer1_area1[];
extern Gfx mat_revert_jrb_dl_wood_tertiary_layer1_area1[];
extern Gfx mat_jrb_dl_windows_layer1_area1[];
extern Gfx mat_revert_jrb_dl_windows_layer1_area1[];
extern Gfx jrb_dl_Level_Mesh_mesh_layer_1[];
extern Gfx jrb_dl_final_revert_mesh_layer_1[];
