extern const GeoLayout ttc_area_1_geo[];
extern const GeoLayout ttc_area_1[];
extern const Collision ttc_area_1_collision[];
extern const MacroObject ttc_area_1_macro_objs[];
extern Lights1 ttc_dl_ground_lights;
extern Lights1 ttc_dl_side_lights;
extern Lights1 ttc_dl_f3dlite_material_007_layer1_area1_lights;
extern u8 ttc_dl_ttc_textures_08400_rgba16_ci8[];
extern u8 ttc_dl_ttc_textures_08400_rgba16_pal_rgba16[];
extern u8 ttc_dl_ttc_textures_03000_rgba16_ci8[];
extern u8 ttc_dl_ttc_textures_03000_rgba16_pal_rgba16[];
extern u8 ttc_dl_ttc_textures_02800_rgba16_ci8[];
extern u8 ttc_dl_ttc_textures_02800_rgba16_pal_rgba16[];
extern u8 ttc_dl_ttc_textures_00000_rgba16_ci8[];
extern u8 ttc_dl_ttc_textures_00000_rgba16_pal_rgba16[];
extern Vtx ttc_dl_ground_mesh_layer_1_vtx_0[12];
extern Gfx ttc_dl_ground_mesh_layer_1_tri_0[];
extern Vtx ttc_dl_ground_mesh_layer_1_vtx_1[44];
extern Gfx ttc_dl_ground_mesh_layer_1_tri_1[];
extern Vtx ttc_dl_ttc_seg7_dl_07009BF0_mesh_mesh_layer_1_vtx_0[236];
extern Gfx ttc_dl_ttc_seg7_dl_07009BF0_mesh_mesh_layer_1_tri_0[];
extern Vtx ttc_dl_upper_mesh_layer_4_vtx_0[104];
extern Gfx ttc_dl_upper_mesh_layer_4_tri_0[];
extern Vtx ttc_dl_upper_mesh_layer_4_vtx_1[32];
extern Gfx ttc_dl_upper_mesh_layer_4_tri_1[];
extern Vtx ttc_dl_wall_kick_mesh_layer_4_vtx_0[40];
extern Gfx ttc_dl_wall_kick_mesh_layer_4_tri_0[];
extern Gfx mat_ttc_dl_ground[];
extern Gfx mat_revert_ttc_dl_ground[];
extern Gfx mat_ttc_dl_side[];
extern Gfx mat_revert_ttc_dl_side[];
extern Gfx mat_ttc_dl_f3dlite_material_007_layer1_area1[];
extern Gfx mat_revert_ttc_dl_f3dlite_material_007_layer1_area1[];
extern Gfx mat_ttc_dl_nocam[];
extern Gfx mat_revert_ttc_dl_nocam[];
extern Gfx mat_ttc_dl_fence[];
extern Gfx mat_revert_ttc_dl_fence[];
extern Gfx ttc_dl_ground_mesh_layer_1[];
extern Gfx ttc_dl_ttc_seg7_dl_07009BF0_mesh_mesh_layer_1_with_revert[];
extern Gfx ttc_dl_upper_mesh_layer_4[];
extern Gfx ttc_dl_wall_kick_mesh_layer_4_with_revert[];
