extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const MacroObject bbh_area_1_macro_objs[];
extern Lights1 bbh_dl_walls_lights;
extern Lights1 bbh_dl_black_lights;
extern Lights1 bbh_dl_floor_lights;
extern Lights1 bbh_dl_grey_lights;
extern u8 bbh_dl__0_rgba16_ci8[];
extern u8 bbh_dl__0_rgba16_pal_rgba16[];
extern u8 bbh_dl_bbh_textures_09000_rgba16_ci8[];
extern u8 bbh_dl_bbh_textures_09000_rgba16_pal_rgba16[];
extern u8 bbh_dl_bbh_textures_03800_rgba16_ci8[];
extern u8 bbh_dl_bbh_textures_03800_rgba16_pal_rgba16[];
extern Vtx bbh_dl_Circle_mesh_layer_1_vtx_0[64];
extern Gfx bbh_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Circle_mesh_layer_1_vtx_1[29];
extern Gfx bbh_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx bbh_dl_Circle_mesh_layer_1_vtx_2[26];
extern Gfx bbh_dl_Circle_mesh_layer_1_tri_2[];
extern Vtx bbh_dl_Circle_mesh_layer_1_vtx_3[112];
extern Gfx bbh_dl_Circle_mesh_layer_1_tri_3[];
extern Gfx mat_bbh_dl_walls[];
extern Gfx mat_revert_bbh_dl_walls[];
extern Gfx mat_bbh_dl_black[];
extern Gfx mat_revert_bbh_dl_black[];
extern Gfx mat_bbh_dl_floor[];
extern Gfx mat_revert_bbh_dl_floor[];
extern Gfx mat_bbh_dl_grey[];
extern Gfx mat_revert_bbh_dl_grey[];
extern Gfx bbh_dl_Circle_mesh_layer_1_with_revert[];
