extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern Lights1 lll_dl_top_lights;
extern Lights1 lll_dl_side_lights;
extern Lights1 lll_dl_side_nonlava_lights;
extern u8 lll_dl_lll_textures_01800_rgba16_ci8[];
extern u8 lll_dl_lll_textures_01800_rgba16_pal_rgba16[];
extern u8 lll_dl_lll_textures_06800_rgba16_rgba16[];
extern u8 lll_dl_lll_textures_06000_rgba16_ci8[];
extern u8 lll_dl_lll_textures_06000_rgba16_pal_rgba16[];
extern u8 lll_dl_lll_textures_09000_rgba16_ci8[];
extern u8 lll_dl_lll_textures_09000_rgba16_pal_rgba16[];
extern Vtx lll_dl_Border_mesh_layer_1_vtx_0[73];
extern Gfx lll_dl_Border_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Border_mesh_layer_1_vtx_1[52];
extern Gfx lll_dl_Border_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Border_mesh_layer_1_vtx_2[72];
extern Gfx lll_dl_Border_mesh_layer_1_tri_2[];
extern Vtx lll_dl_Corner_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Corner_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Corner_mesh_layer_1_vtx_1[16];
extern Gfx lll_dl_Corner_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Corner_001_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Corner_001_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Corner_001_mesh_layer_1_vtx_1[16];
extern Gfx lll_dl_Corner_001_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Lava_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Lava_mesh_layer_1_tri_0[];
extern Gfx mat_lll_dl_top[];
extern Gfx mat_revert_lll_dl_top[];
extern Gfx mat_lll_dl_side[];
extern Gfx mat_revert_lll_dl_side[];
extern Gfx mat_lll_dl_side_nonlava[];
extern Gfx mat_revert_lll_dl_side_nonlava[];
extern Gfx mat_lll_dl_Lava[];
extern Gfx mat_revert_lll_dl_Lava[];
extern Gfx lll_dl_Border_mesh_layer_1[];
extern Gfx lll_dl_Corner_mesh_layer_1[];
extern Gfx lll_dl_Corner_001_mesh_layer_1[];
extern Gfx lll_dl_Lava_mesh_layer_1_with_revert[];
