extern const GeoLayout ingredients_geo_opt_1[];
extern const GeoLayout ingredients_geo_opt_2[];
extern const GeoLayout ingredients_geo_opt_3[];
extern const GeoLayout ingredients_geo_opt_4[];
extern const GeoLayout ingredients_geo_opt_5[];
extern const GeoLayout ingredients_geo_opt_6[];
extern const GeoLayout ingredients_geo_opt_7[];
extern const GeoLayout ingredients_geo_opt_8[];
extern const GeoLayout ingredients_geo[];
extern Lights1 ingredients_tomato_chopped_lights;
extern u8 ingredients_unchopped_lettuce_rgba16[];
extern u8 ingredients_chopped_lettuce_ci8[];
extern u8 ingredients_chopped_lettuce_pal_rgba16[];
extern u8 ingredients_unchopped_tomato_rgba16[];
extern u8 ingredients_chopped_tomato_ci8[];
extern u8 ingredients_chopped_tomato_pal_rgba16[];
extern u8 ingredients_unchopped_cheese_rgba16[];
extern u8 ingredients_chopped_cheese_rgba16[];
extern u8 ingredients_unchopped_meat_raw_rgba16[];
extern u8 ingredients_chopped_meat_raw_ci8[];
extern u8 ingredients_chopped_meat_raw_pal_rgba16[];
extern u8 ingredients_chopped_meat_cooked_rgba16[];
extern Vtx ingredients_ingredient_dl_mesh_layer_5_vtx_0[4];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_tri_0[];
extern Gfx mat_ingredients_lettuce_unchopped[];
extern Gfx mat_revert_ingredients_lettuce_unchopped[];
extern Gfx mat_ingredients_lettuce_chopped[];
extern Gfx mat_revert_ingredients_lettuce_chopped[];
extern Gfx mat_ingredients_tomato_unchopped[];
extern Gfx mat_revert_ingredients_tomato_unchopped[];
extern Gfx mat_ingredients_tomato_chopped[];
extern Gfx mat_revert_ingredients_tomato_chopped[];
extern Gfx mat_ingredients_cheese_unchopped[];
extern Gfx mat_revert_ingredients_cheese_unchopped[];
extern Gfx mat_ingredients_cheese_chopped[];
extern Gfx mat_revert_ingredients_cheese_chopped[];
extern Gfx mat_ingredients_meat_unchopped_raw[];
extern Gfx mat_revert_ingredients_meat_unchopped_raw[];
extern Gfx mat_ingredients_meat_chopped_raw[];
extern Gfx mat_revert_ingredients_meat_chopped_raw[];
extern Gfx mat_ingredients_meat_chopped_cooked[];
extern Gfx mat_revert_ingredients_meat_chopped_cooked[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_1_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_2_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_3_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_4_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_5_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_6_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_7_with_revert[];
extern Gfx ingredients_ingredient_dl_mesh_layer_5_opt_8_with_revert[];
