extern const GeoLayout pot_pot_liquid_switch_opt1[];
extern const GeoLayout pot_pot_liquid_switch_opt2[];
extern const GeoLayout pot_pot_liquid_switch_opt3[];
extern const GeoLayout pot_geo[];
extern Lights1 pot_pot_lights;
extern Lights1 pot_pot_liquid_onion_lights;
extern Lights1 pot_pot_liquid_mushroom_lights;
extern Lights1 pot_pot_liquid_tomato_lights;
extern Lights1 pot_pot_liquid_burnt_lights;
extern u8 pot_pot_liquid_burnt_ci8[];
extern u8 pot_pot_liquid_burnt_pal_rgba16[];
extern Vtx pot_pot_dl_mesh_layer_1_vtx_0[235];
extern Gfx pot_pot_dl_mesh_layer_1_tri_0[];
extern Vtx pot_pot_liquid_model_mesh_layer_1_vtx_0[10];
extern Gfx pot_pot_liquid_model_mesh_layer_1_tri_0[];
extern Gfx mat_pot_pot[];
extern Gfx mat_revert_pot_pot[];
extern Gfx mat_pot_pot_liquid_onion[];
extern Gfx mat_revert_pot_pot_liquid_onion[];
extern Gfx mat_pot_pot_liquid_mushroom[];
extern Gfx mat_revert_pot_pot_liquid_mushroom[];
extern Gfx mat_pot_pot_liquid_tomato[];
extern Gfx mat_revert_pot_pot_liquid_tomato[];
extern Gfx mat_pot_pot_liquid_burnt[];
extern Gfx mat_revert_pot_pot_liquid_burnt[];
extern Gfx pot_pot_dl_mesh_layer_1[];
extern Gfx pot_pot_liquid_model_mesh_layer_1[];
extern Gfx pot_pot_liquid_model_mesh_layer_1_mat_override_pot_liquid_mushroom_0[];
extern Gfx pot_pot_liquid_model_mesh_layer_1_mat_override_pot_liquid_tomato_1[];
extern Gfx pot_pot_liquid_model_mesh_layer_1_mat_override_pot_liquid_burnt_2[];
extern Gfx pot_material_revert_render_settings[];
