const GeoLayout mixer_mixer_bowl_switch_option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mixer_mixer_bowl_switch_option_mixer_bowl_model_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mixer_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(50, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, mixer_bowl_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, mixer_mixer_bowl_switch_option),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mixer_mixer_model_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mixer_mixer_model_mesh_layer_5),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -127, 254, 0, mixer_mixer_spin_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mixer_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mixer_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
