extern const GeoLayout mixer_mixer_bowl_switch_option[];
extern const GeoLayout mixer_geo[];
extern Lights1 mixer_f3dlite_material_002_lights;
extern Lights1 mixer_f3dlite_material_001_lights;
extern Lights1 mixer_f3dlite_material_003_lights;
extern u8 mixer_mixer_purple_ci8[];
extern u8 mixer_mixer_purple_pal_rgba16[];
extern Vtx mixer_mixer_bowl_switch_option_mixer_bowl_model_mesh_layer_1_vtx_0[103];
extern Gfx mixer_mixer_bowl_switch_option_mixer_bowl_model_mesh_layer_1_tri_0[];
extern Vtx mixer_mixer_model_mesh_layer_1_vtx_0[109];
extern Gfx mixer_mixer_model_mesh_layer_1_tri_0[];
extern Vtx mixer_mixer_model_mesh_layer_1_vtx_1[167];
extern Gfx mixer_mixer_model_mesh_layer_1_tri_1[];
extern Vtx mixer_mixer_model_mesh_layer_5_vtx_0[94];
extern Gfx mixer_mixer_model_mesh_layer_5_tri_0[];
extern Vtx mixer_mixer_spin_mesh_layer_1_vtx_0[70];
extern Gfx mixer_mixer_spin_mesh_layer_1_tri_0[];
extern Gfx mat_mixer_f3dlite_material_002[];
extern Gfx mat_revert_mixer_f3dlite_material_002[];
extern Gfx mat_mixer_f3dlite_material_001[];
extern Gfx mat_revert_mixer_f3dlite_material_001[];
extern Gfx mat_mixer_f3dlite_material_003[];
extern Gfx mat_revert_mixer_f3dlite_material_003[];
extern Gfx mixer_mixer_bowl_switch_option_mixer_bowl_model_mesh_layer_1[];
extern Gfx mixer_mixer_model_mesh_layer_1[];
extern Gfx mixer_mixer_model_mesh_layer_5[];
extern Gfx mixer_mixer_spin_mesh_layer_1[];
extern Gfx mixer_material_revert_render_settings[];
