extern const GeoLayout plate_plate_soup_onion[];
extern const GeoLayout plate_plate_soup_mushroom[];
extern const GeoLayout plate_plate_soup_tomato[];
extern const GeoLayout plate_plate_soup_burnt[];
extern const GeoLayout plate_plate_switch_opt1[];
extern const GeoLayout plate_geo[];
extern Lights1 plate_pot_liquid_onion_lights;
extern Lights1 plate_pot_liquid_mushroom_lights;
extern Lights1 plate_pot_liquid_tomato_lights;
extern Lights1 plate_pot_liquid_burnt_lights;
extern Lights1 plate_plate_lights;
extern Lights1 plate_plate_bottom_lights;
extern Lights1 plate_plate_dirty_lights;
extern u8 plate_pot_liquid_burnt_ci8[];
extern u8 plate_pot_liquid_burnt_pal_rgba16[];
extern u8 plate_blank_i8[];
extern u8 plate_plate_dirty_ci8[];
extern u8 plate_plate_dirty_pal_rgba16[];
extern Vtx plate_plate_soup_onion_so_plate_soup_onion_mdl_mesh_layer_1_vtx_0[11];
extern Gfx plate_plate_soup_onion_so_plate_soup_onion_mdl_mesh_layer_1_tri_0[];
extern Vtx plate_plate_soup_mushroom_so_plate_soup_mushroom_mdl_mesh_layer_1_vtx_0[11];
extern Gfx plate_plate_soup_mushroom_so_plate_soup_mushroom_mdl_mesh_layer_1_tri_0[];
extern Vtx plate_plate_soup_tomato_so_plate_soup_tomato_mdl_mesh_layer_1_vtx_0[11];
extern Gfx plate_plate_soup_tomato_so_plate_soup_tomato_mdl_mesh_layer_1_tri_0[];
extern Vtx plate_plate_soup_burnt_so_plate_soup_burnt_mdl_mesh_layer_1_vtx_0[11];
extern Gfx plate_plate_soup_burnt_so_plate_soup_burnt_mdl_mesh_layer_1_tri_0[];
extern Vtx plate_plate_dl_mesh_layer_1_vtx_0[50];
extern Gfx plate_plate_dl_mesh_layer_1_tri_0[];
extern Vtx plate_plate_dl_mesh_layer_1_vtx_1[50];
extern Gfx plate_plate_dl_mesh_layer_1_tri_1[];
extern Gfx mat_plate_pot_liquid_onion[];
extern Gfx mat_revert_plate_pot_liquid_onion[];
extern Gfx mat_plate_pot_liquid_mushroom[];
extern Gfx mat_revert_plate_pot_liquid_mushroom[];
extern Gfx mat_plate_pot_liquid_tomato[];
extern Gfx mat_revert_plate_pot_liquid_tomato[];
extern Gfx mat_plate_pot_liquid_burnt[];
extern Gfx mat_revert_plate_pot_liquid_burnt[];
extern Gfx mat_plate_plate[];
extern Gfx mat_revert_plate_plate[];
extern Gfx mat_plate_plate_bottom[];
extern Gfx mat_revert_plate_plate_bottom[];
extern Gfx mat_plate_plate_dirty[];
extern Gfx mat_revert_plate_plate_dirty[];
extern Gfx plate_plate_soup_onion_so_plate_soup_onion_mdl_mesh_layer_1[];
extern Gfx plate_plate_soup_mushroom_so_plate_soup_mushroom_mdl_mesh_layer_1[];
extern Gfx plate_plate_soup_tomato_so_plate_soup_tomato_mdl_mesh_layer_1[];
extern Gfx plate_plate_soup_burnt_so_plate_soup_burnt_mdl_mesh_layer_1[];
extern Gfx plate_plate_dl_mesh_layer_1[];
extern Gfx plate_plate_dl_mesh_layer_1_mat_override_plate_dirty_0[];
extern Gfx plate_material_revert_render_settings[];
