extern const GeoLayout plate_plate_soup_switch_opt1[];
extern const GeoLayout plate_plate_soup_switch_opt2[];
extern const GeoLayout plate_plate_soup_switch_opt3[];
extern const GeoLayout plate_plate_soup_switch_opt4[];
extern const GeoLayout plate_plate_switch_opt1[];
extern const GeoLayout plate_geo[];
extern Lights1 plate_pot_liquid_onion_lights;
extern Lights1 plate_pot_liquid_mushroom_lights;
extern Lights1 plate_pot_liquid_tomato_lights;
extern Lights1 plate_pot_liquid_burnt_lights;
extern Lights1 plate_plate_lights;
extern Lights1 plate_plate_bottom_lights;
extern Lights1 plate_plate_dirty_lights;
extern u8 plate_pot_liquid_burnt_ci8[];
extern u8 plate_pot_liquid_burnt_pal_rgba16[];
extern u8 plate_blank_i8[];
extern u8 plate_plate_dirty_ci8[];
extern u8 plate_plate_dirty_pal_rgba16[];
extern Vtx plate_plate_soup_dl_mesh_layer_4_vtx_0[10];
extern Gfx plate_plate_soup_dl_mesh_layer_4_tri_0[];
extern Vtx plate_plate_dl_mesh_layer_1_vtx_0[50];
extern Gfx plate_plate_dl_mesh_layer_1_tri_0[];
extern Vtx plate_plate_dl_mesh_layer_1_vtx_1[50];
extern Gfx plate_plate_dl_mesh_layer_1_tri_1[];
extern Gfx mat_plate_pot_liquid_none[];
extern Gfx mat_revert_plate_pot_liquid_none[];
extern Gfx mat_plate_pot_liquid_onion[];
extern Gfx mat_revert_plate_pot_liquid_onion[];
extern Gfx mat_plate_pot_liquid_mushroom[];
extern Gfx mat_revert_plate_pot_liquid_mushroom[];
extern Gfx mat_plate_pot_liquid_tomato[];
extern Gfx mat_revert_plate_pot_liquid_tomato[];
extern Gfx mat_plate_pot_liquid_burnt[];
extern Gfx mat_revert_plate_pot_liquid_burnt[];
extern Gfx mat_plate_plate[];
extern Gfx mat_revert_plate_plate[];
extern Gfx mat_plate_plate_bottom[];
extern Gfx mat_revert_plate_plate_bottom[];
extern Gfx mat_plate_plate_dirty[];
extern Gfx mat_revert_plate_plate_dirty[];
extern Gfx plate_plate_soup_dl_mesh_layer_4[];
extern Gfx plate_plate_soup_dl_mesh_layer_4_mat_override_pot_liquid_onion_0[];
extern Gfx plate_plate_soup_dl_mesh_layer_4_mat_override_pot_liquid_mushroom_1[];
extern Gfx plate_plate_soup_dl_mesh_layer_4_mat_override_pot_liquid_tomato_2[];
extern Gfx plate_plate_soup_dl_mesh_layer_4_mat_override_pot_liquid_burnt_3[];
extern Gfx plate_plate_dl_mesh_layer_1[];
extern Gfx plate_plate_dl_mesh_layer_1_mat_override_plate_dirty_0[];
extern Gfx plate_material_revert_render_settings[];
